config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' } do
    get "/users/sign_out" => "devise/sessions#destroy"
  end
  # devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :bars do
    get 'favorite', on: :member
    get 'unfavorite', on: :member
    #member is a ruby native syntax. A member route will require an ID, because it acts on a member
    resources :promos
  end
  get 'favorites' => "favorites#index"
  root to: "bars#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bar.rb
# frozen_string_literal: true

class Bar < ApplicationRecord
  has_and_belongs_to_many :categories
  belongs_to :owner, class_name: :User, foreign_key: :owner_id
  acts_as_favoritable
  has_many :promos
end

app/controllers/bars_controller.rb
# frozen_string_literal: true

class BarsController < ApplicationController

  #doing the set bar allows it to universally adopt the private properties for the crud + fav for the setbar.
  before_action :set_bar, only: [:show, :edit, :update, :destroy, :favorite, :unfavorite]
  before_action :authenticate_user!, except: [:show, :index]
  protect_from_forgery except: [:getdistance]

  # GET /bars
  # GET /bars.json
  def index
    @bars = Bar.all.order(created_at: :desc)
    @users = User.all
    @page_title = 'Bars'
    #make the header dynamic
  end

  # GET /bars/1
  # GET /bars/1.json
  def show
    @promos = @bar.promos
    # @category = Category.all

  end

  # GET /bars/new
  def new
    @bar = Bar.new
    @categories = Category.all
    @owners = Owner.all
  end

  # GET /bars/1/edit
  def edit
    @bar = Bar.find(params[:id])
    @categories = Category.all
    @owners = Owner.all
  end

  # POST /bars
  # POST /bars.json
  def create

    @bar = Bar.new(bar_params)
    uploaded_file = params[:bar][:image].path
    cloudinary_file = Cloudinary::Uploader.upload(uploaded_file, :folder => "quick-pint")
    @bar.attributes = {:image => cloudinary_file["public_id"]}

    if @bar.save == true
      redirect_to @bar
    else
      render 'new'
    end

    # respond_to do |format|
    #   if @bar.save
    #     format.html { redirect_to @bar, notice: "Bar was successfully created." }
    #     format.json { render :show, status: :created, location: @bar }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @bar.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /bars/1
  # PATCH/PUT /bars/1.json
  def update

      @bar = Bar.find(params[:id])
      if params[:bar][:image] #insert this into quickpint
        uploaded_file = params[:bar][:image].path
        cloudinary_file = Cloudinary::Uploader.upload(uploaded_file, :folder => "quick-pint")
        puts cloudinary_file["public_id"]
        @bar.attributes = {:image => cloudinary_file["public_id"]}
        p @bar
      else
        bar_params[:image] = @bar.image #insert this into quickpint
      end
    respond_to do |format|
      if @bar.update(bar_params)
        if params[:bar][:image]
          @bar.update(image: cloudinary_file["public_id"])
          format.html { redirect_to @bar, notice: 'Bar was successfully updated.' }
          format.json { render :show, status: :ok, location: @bar }
        else
          bar_params[:image] = @bar.image #insert this into quickpint
          format.html { redirect_to @bar, notice: 'Bar was successfully updated.' }
          format.json { render :show, status: :ok, location: @bar }
        end
      else
        format.html { render :edit }
        format.json { render json: @bar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bars/1
  # DELETE /bars/1.json
  def destroy
    @bar.destroy
    respond_to do |format|
      format.html { redirect_to bars_url, notice: 'Bar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def favorite
    current_user.favorite(@bar)
    redirect_back(fallback_location:root_path)
  end

  def unfavorite
    current_user.unfavorite(@bar)
    #write conditions to find which page i'm on and redirect me to favorites page instead of returning back to index
    redirect_back(fallback_location:root_path)

  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_bar
    @bar = Bar.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def bar_params
    params.require(:bar).permit(:name, :image, :address, :business_hours, :place_id, :lat, :long, :avg_price, :owner_id, :category_ids => [])
  end
end

app/helpers/bars_helper.rb
module BarsHelper
end

app/views/bars/_form.html.erb
<%= form_with(model: bar, local: true) do |form| %>
  <% if bar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bar.errors.count, "error") %> prohibited this bar from being saved:</h2>

      <ul>
      <% bar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :business_hours %>
    <%= form.text_field :business_hours %>
  </div>

  <div class="field">
    <%= form.label :images %>
    <%= form.text_field :images %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bars/create_confirm.html.erb
<style>
	#map{
		border: 1px solid black;
		height: 300px;
		width: 400px;
	}
	input{
		width: 200px;
	}
</style>

<input></input>

<div id="map"></div>
<script src="/script.js"></script>
<script async type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC4vP8QnuK9A88LyIbgE9BzQw9G-1lMsGc&libraries=places&callback=initMap"></script>

<table id="bar_details">
  <tr>
    <td class="label">Name</td>
    <td class="slimField"><input class="field" id="name" disabled="true"/></td>
  </tr>
  <tr>
    <td class="label">Address</td>
    <td class="wideField" colspan="3"><input class="field" id="address" disabled="true"/></td>
  </tr>
  <tr>
    <td class="label">Image</td>
    <td class="slimField"><input class="field" id="image" disabled="true"/></td>
  </tr>
  <tr>
    <td class="label">Business Hour</td>
    <td class="wideField" colspan="3"><input class="field" id="business_hour" disabled="true"/></td>
  </tr>
  <tr>
    <td class="label">Closing Hour</td>
    <td class="wideField" colspan="3"><input class="field" id="closing_hour" disabled="true"/></td>
  </tr>
  <tr>
    <td class="label">Type</td>
    <td class="wideField" colspan="3"><input class="field" id="type" disabled="true"/></td>
  </tr>
</table>

app/views/bars/edit.html.erb
<h1>Editing Bar</h1>

<%= form_with scope: :bar, model: @bar, local: true do |form| %>
  <p>
    <%= form.label :name, 'Bar Name' %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :business_hours, 'Business Hours' %><br>
    <%= form.text_field :business_hours %>
  </p>

	<%= cl_image_tag(@bar.image) %><br>

  <p>
 		<%= form.label :image, 'Upload Bar Image' %><br>
		<%= form.file_field :image %>
  </p>

  <p>
  	 <%= form.label :address, 'Bar Address' %><br>
    <%= form.text_field :address %>
  </p>

	<p>
    <%= form.hidden_field :place_id %>
    <%= form.hidden_field :lat, class: :text_field, step: :any  %>
    <%= form.hidden_field :long, class: :text_field, step: :any  %>
  </p>

	<p>
    <%= form.label :avg_price, 'Average Price (S$)' %><br>
    <%= form.number_field :avg_price, class: :text_field, step: :any %>
  </p>

	<p>
    <%= form.label :category_id, 'Type of Bar' %><br>
    <%= form.collection_check_boxes :category_ids, @categories, :id, :name %>
  </p>

	<p>
    <%= form.label :owner_id, 'Owner Bar' %><br>
    <%= form.collection_select :owner_id, @owners, :id, :name %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', bars_path, class: 'btn btn-secondary' %>
<%= link_to 'Destroy', bar_path(@bar),
        			method: :delete,
        			data: { confirm: 'Are you sure you want to delete this bar?' },
							class: 'btn btn-secondary' %>

app/views/bars/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<div class="page-header-container">
  <header>bars</header>
</div>

        <!--
          [48-(3*4)]/3 = 12
          12 * 30 = 360
        -->
        <div id="bars-list" class="bars-list" style="margin-bottom: 90px;">
          <% @bars.each do |bar| %>
            <%= link_to bar_path(bar), :action => 'go' do %>
              <div class="card-container">
                <div class="card-body">
                  <div class="card-image">
                    <% if bar.image == nil %>
                      <%= '' %>
                    <% else %>
                      <%= cl_image_tag(bar.image) %>
                    <% end %>
                  </div>
                  <div class="card-details">
                    <h1><%= bar.name %></h1>
                    <p>
                      <div class="left-text">Distance</div>
                      <div class='latLong right-text' style='visibility:hidden'>
                        <%= bar.lat %>, <%= bar.long %>
                      </div>
                      <div class="dotted"></div>
                    </p>

                    <p>
                      <div class="left-text">Price per pint</div>
                      <div class="right-text price">$<%= bar.avg_price %></div>
                      <div class="dotted"></div>
                    </p>
                  </div>
                </div>
                <div class="card-promos">
                  <%# if happy hour available lmao %>
                    <div class="card-promos-text">
                      Happy Hour available!
                    </div>
                </div>
                <div class="card-favorite">
                  <%# if haven't fav %>
                  <% if user_signed_in? %>
                    <% if current_user.favorited?(bar) %>
                      <%= link_to image_tag('faved.png', width: 35), unfavorite_bar_path(bar) %>
                    <% else %>
                      <%= link_to image_tag('fav.png', width: 35), favorite_bar_path(bar) %>
                    <% end %>
                  <% else %>
                    <%= link_to image_tag('fav.png', width: 35), new_user_registration_path %>
                  <% end %>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>

        <%# Conditionals for different users %>

        <%#= link_to 'Show', bar_path(bar), class: 'btn btn-secondary' %>

        <%# Checks if user is owner of bar %>
        <%# if user_signed_in? && current_user.id == bar.owner_id %>
          <%#= link_to 'Edit', edit_bar_path(bar), class: 'btn btn-secondary' %>
          <%#= link_to 'Destroy', bar, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-secondary' %>
        <%# end %>

app/views/bars/new.html.erb
<div class="page-header-container">
  <header>new bar</header>
</div>

<style>
	#map {
		border: 3px solid black;
		margin: 10px 0px 20px 0px;
		height: 400px;
		width: 690px;
	}
</style>


<div class='form-position'>
<%= form_with scope: :bar, url: bars_path, local: true do |form| %>

  <input id='autoComplete'></input>

  <div id='map'></div>
  <script async type='text/javascript' src='https://maps.googleapis.com/maps/api/js?key=AIzaSyC4vP8QnuK9A88LyIbgE9BzQw9G-1lMsGc&libraries=places&callback=initMap'></script>

  <p>
    <%= form.text_field :name, id:'name', placeholder: 'Bar Name' %>
  </p>

	<p>
    <%= form.text_field :business_hours, id:'hours', placeholder: 'Business Hours' %>
  </p>

  <p>
    <%= form.text_field :address, id:'address', placeholder: 'Bar Address' %>
  </p>

	<p>
    <%= form.file_field :image %>
  </p>

	<p>
    <%= form.number_field :avg_price, class: :text_field, step: :any, placeholder: 'Average Price Per Pint' %>
  </p>

	<p>
    <%= form.label :category_id, 'Type of Bar' %><br>
    <ul>
      <%= form.collection_check_boxes :category_ids, @categories, :id, :name %>
    </ul>
  </p>

    <%= form.hidden_field :owner_id, :value => current_user.id%>
    <%= form.hidden_field :place_id, id:'place_id' %>
    <%= form.hidden_field :lat, class: :text_field, step: :any, id:'lat'  %>
    <%= form.hidden_field :long, class: :text_field, step: :any, id:'long'  %>

	<p>
    <%= form.submit %>
  </p>
<% end %>
</div>

app/views/bars/show.html.erb
<style>
  #map {
    border: 1px solid black;
    margin: 35px auto 0 auto;
    height: 300px;
    width: 85%;
  }

  .show-left-text,.show-right-text {
  padding: 1px 45px 1px 5px;
  background: #fff;
  float: right;
  height: 1em;
  margin-top: -5px;
}

.show-left-text {
  padding: 1px 5px 1px 45px;
  float: left;
  clear: both;
  height: 1em;
}

.show-dotted {
  margin-top: -5px;
  margin-bottom: 2px;
  height: 1em;
  background-image: linear-gradient(to right, black 15%, rgba(255, 255, 255, 0) 0%);
  background-position: bottom;
  background-size: 10px 1px;
  background-repeat: repeat-x;
}

.show-bar-buttons {
  position: fixed;
  right: 86.5px;
  top: 28.5px;
}

.show-bar-buttons>* {
  display: inline-block;
  margin-left: -7px;
}
</style>
<script async type='text/javascript' src='https://maps.googleapis.com/maps/api/js?key=AIzaSyC4vP8QnuK9A88LyIbgE9BzQw9G-1lMsGc&libraries=places&callback=initMap'></script>
<p id='notice'>
  <%= notice %>
</p>
<div class="page-header-container">
  <header id="placeName">
    <%= @bar.name %>
  </header>
  <span id="placeId" style="display: none;">
    <%= @bar.place_id %></span>
  <span id="latitude" style="display: none;">
    <%= @bar.lat %></span>
  <span id="longitude" style="display: none;">
    <%= @bar.long %></span>
</div>
<div class="show-bar-container">
  <div class="show-bar-layer">
    <div class="show-bar-photos-label" style="display: inline-block;">
      <h2>Photo</h2>
    </div>
    <div class="show-bar-categories" style="display: inline-block;">
      <h2>
        <% @bar.categories.each do |cat| %>
        <% if cat.equal? @bar.categories.last %>
        <%= cat.name %>
        <% else %>
        <%= cat.name %>,
        <% end %>
        <% end %>
      </h2>
    </div>
    <div class="show-bar-favorite" style="display: inline-block;">
      <div class="icon-border">
        <div class="absolute-center">
          <% if user_signed_in? %>
          <% if current_user.favorited?(@bar) %>
          <%= link_to image_tag('faved.png', width: 35), unfavorite_bar_path(@bar) %>
          <% else %>
          <%= link_to image_tag('fav.png', width: 35), favorite_bar_path(@bar) %>
          <% end %>
          <% else %>
          <%= link_to image_tag('fav.png', width: 35), new_user_registration_path %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="show-bar-layer">
    <div class="show-bar-image">
      <% if @bar.image == nil %>
      <%= '' %>
      <% else %>
      <%= cl_image_tag(@bar.image) %>
      <% end %>
    </div>
    <div class="show-bar-hh">
      <h3>Happy Hour now!</h3>
    </div>
  </div>
  <div class="show-bar-layer">
    <div class="show-bar-location label-before-body">
      <h4>Location</h4>
    </div>
    <div class="show-bar-location body-after-label">
      <p>
        <div class="show-left-text">Address</div>
        <div class="show-right-text">
          <%= @bar.address %>
        </div>
        <div class="show-dotted"></div>
      </p>
      <div id='map'></div>
    </div>
  </div>
  <div class="show-bar-layer">
    <div class="show-bar-business-hours body-before-label">
      <% @bar.business_hours.split(',').each do |day| %>
      <% daySplit = day.split(': ') %>
      <p>
        <div class="show-left-text">
          <%= daySplit[0] %>
        </div>
        <div class="show-right-text">
          <%= daySplit[1] %>
        </div>
        <div class="show-dotted"></div>
      </p>
      <% end %>
    </div>
    <div class="show-bar-business-hours label-after-body">
      <h3>Business hours</h3>
    </div>
  </div>
  <div class="show-bar-layer">
    <div class="show-bar-promos label-before-body">
      <h4>Promos</h4>
    </div>
    <div class="show-bar-promos body-after-label">
      <% if @promos.present? %>
      <% @promos.each do |promo| %>
      <p>
        <div class="show-left-text">
          <%= promo.name %>
        </div>
        <div class="show-right-text">
          <%= promo.detail %>
        </div>
        <div class="show-dotted"></div>
      </p>
      <% end %>
      <% else %>
      <p>No promotions available right now</p>
      <% end %>
    </div>
  </div>
</div>
<%# Checks if user is owner of bar %>
<% if user_signed_in? && current_user.id == @bar.owner_id %>
<div class="show-bar-buttons">
  <span class="span-style" style="font-size: 21px;">
    <%= link_to 'Edit', edit_bar_path(@bar), class: 'btn btn-secondary' %>
  </span>
  <span class="span-style" style="font-size: 21px;">
    <%= link_to 'Destroy', @bar, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-secondary' %>
  </span>
  <span class="span-style" style="font-size: 21px;">
    <%= link_to 'Add Promotion', new_bar_promo_path(@bar) %>
  </span>
</div>
<% end %>